# -*- coding: utf-8 -*-
"""
/***************************************************************************
 doorknockplanner
                                 A QGIS plugin
 Maps and prioritised police door knocking activities
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-09-25
        copyright            : (C) 2025 by Darren Green
        email                : Green.DarrenS@police.qld.gov.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Darren Green'
__date__ = '2025-09-25'
__copyright__ = '(C) 2025 by Darren Green'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load doorknockplanner class from file doorknockplanner.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .door_knock_planner import doorknockplannerPlugin
    return doorknockplannerPlugin()
